// Pont sécurisé entre le renderer et le process principal.
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('skanfact', {
  loadData: () => ipcRenderer.invoke('data:load'),
  saveData: (data, force) => ipcRenderer.invoke('data:save', { data, force: !!force }),
  listDossiers: () => ipcRenderer.invoke('dossiers:list'),
  switchDossier: (id) => ipcRenderer.invoke('dossiers:switch', id),
  addDossier: (o) => ipcRenderer.invoke('dossiers:add', o),
  shareDossier: () => ipcRenderer.invoke('dossiers:share'),
  joinDossier: () => ipcRenderer.invoke('dossiers:join'),
  renameDossier: (o) => ipcRenderer.invoke('dossiers:rename', o),
  forgetDossier: (id) => ipcRenderer.invoke('dossiers:forget', id),
  renameDevice: (name) => ipcRenderer.invoke('device:rename', name),
  dataPath: () => ipcRenderer.invoke('data:path'),
  exportData: (data) => ipcRenderer.invoke('data:export', data),
  importData: (opts) => ipcRenderer.invoke('data:import', opts),
  unlock: (password) => ipcRenderer.invoke('data:unlock', password),
  lock: () => ipcRenderer.invoke('data:lock'),
  securityInfo: () => ipcRenderer.invoke('data:security'),
  setPassword: (opts) => ipcRenderer.invoke('data:setPassword', opts),
  externalBackupInfo: () => ipcRenderer.invoke('backups:externalInfo'),
  setExternalBackup: (dir) => ipcRenderer.invoke('backups:setExternal', dir),
  chooseExternalBackup: () => ipcRenderer.invoke('backups:chooseExternal'),
  openBackups: () => ipcRenderer.invoke('backups:open'),
  createBackup: (label) => ipcRenderer.invoke('backups:create', label),
  setTitle: (title) => ipcRenderer.send('window:title', title),
  setDirty: (dirty) => ipcRenderer.send('window:dirty', !!dirty),
  listBackups: () => ipcRenderer.invoke('backups:list'),
  // Regarder une sauvegarde avant de s'en servir, puis la remettre en place (7.0.0). Deux appels
  // distincts exprès : on dit ce qu'on va perdre AVANT d'écraser quoi que ce soit.
  peekBackup: (name) => ipcRenderer.invoke('backups:peek', name),
  restoreBackup: (name) => ipcRenderer.invoke('backups:restore', name),
  pickLogo: (title) => ipcRenderer.invoke('logo:pick', title),
  exportPdf: (html, suggestedName) => ipcRenderer.invoke('pdf:export', { html, suggestedName }),
  exportPdfMany: (files, folderName) => ipcRenderer.invoke('pdf:exportMany', { files, folderName }),
  saveText: (suggestedName, content) => ipcRenderer.invoke('file:saveText', { suggestedName, content }),
  exportPdfSilent: (html, name) => ipcRenderer.invoke('pdf:exportSilent', { html, name }),
  saveTextSilent: (name, content) => ipcRenderer.invoke('file:saveSilent', { name, content }),
  composeMail: (opts) => ipcRenderer.invoke('mail:compose', opts),
  addAttachments: (docId) => ipcRenderer.invoke('attach:add', docId),
  // Lecture d'une photo de facture (4.2.0). `ocrRead` est le SEUL appel qui sort de l'ordinateur,
  // et il échoue proprement tant qu'aucune clé n'a été saisie.
  attachPath: (docId, path) => ipcRenderer.invoke('attach:addPath', { docId, path }),
  ocrStatus: () => ipcRenderer.invoke('ocr:status'),
  ocrSetKey: (key, model) => ipcRenderer.invoke('ocr:setKey', { key, model }),
  ocrPick: () => ipcRenderer.invoke('ocr:pick'),
  ocrRead: (path) => ipcRenderer.invoke('ocr:read', { path }),
  openAttachment: (docId, file) => ipcRenderer.invoke('attach:open', { docId, file }),
  revealAttachment: (docId, file) => ipcRenderer.invoke('attach:reveal', { docId, file }),
  removeAttachment: (docId, file) => ipcRenderer.invoke('attach:remove', { docId, file }),
  openPath: (p) => ipcRenderer.invoke('shell:open', p),
  showInFolder: (p) => ipcRenderer.invoke('shell:showInFolder', p),
  buildPack: (payload) => ipcRenderer.invoke('pack:build', payload),
  importCabinet: () => ipcRenderer.invoke('cabinet:import'),
  licenceStatus: (matricule) => ipcRenderer.invoke('licence:status', { matricule }),
  licenceSet: (key, matricule) => ipcRenderer.invoke('licence:set', key, { matricule }),
  licenceMail: (company, device) => ipcRenderer.invoke('licence:requestMail', { company, device }),
  // L'éditeur (7.33.0). Ce qui repasse ce pont est un état ou une clé « SKAN1.… » signée : la clé
  // privée, elle, reste dans le processus principal.
  licenceEmettre: (payload) => ipcRenderer.invoke('licence:emettre', payload),
  editeurStatus: (depuis) => ipcRenderer.invoke('editeur:status', { depuis }),
  editeurKeygen: () => ipcRenderer.invoke('editeur:keygen'),
  editeurImporter: () => ipcRenderer.invoke('editeur:importer'),
  editeurExporter: () => ipcRenderer.invoke('editeur:exporter'),
  editeurCopierPublique: () => ipcRenderer.invoke('editeur:copierPublique'),
  cleReponseCreer: () => ipcRenderer.invoke('editeur:cleReponseCreer'),
  cleReponseCopier: (quoi) => ipcRenderer.invoke('editeur:cleReponseCopier', quoi),
  cleServeurCreer: () => ipcRenderer.invoke('editeur:cleServeurCreer'),
  cleServeurCopier: (quoi) => ipcRenderer.invoke('editeur:cleServeurCopier', quoi),
  onPackProgress: (cb) => { ipcRenderer.on('pack:progress', (_e, d) => cb(d)); },
  changelog: () => ipcRenderer.invoke('app:changelog'),
  // Battement de cœur du chien de garde (6.6.0) : le processus principal demande « tu es là ? »,
  // l'interface répond. Sans réponse, c'est qu'elle est bloquée — et un gel ne laisse aucune autre trace.
  onAlivePing: (cb) => { ipcRenderer.on('alive:ping', () => { ipcRenderer.send('alive:pong'); if (cb) cb(); }); },
  onFreezeNotice: (cb) => { ipcRenderer.on('freeze:notice', (_e, d) => cb(d)); },
  supportInfo: () => ipcRenderer.invoke('support:info'),
  openLog: () => ipcRenderer.invoke('support:openLog'),
  onMenuAction: (cb) => { ipcRenderer.on('menu:action', (_e, name) => cb(name)); },
  // mises à jour
  updateVersion: () => ipcRenderer.invoke('update:version'),
  updateCheck: () => ipcRenderer.invoke('update:check'),
  updateDownload: () => ipcRenderer.invoke('update:download'),
  updateInstall: () => ipcRenderer.invoke('update:install'),
  updateSetToken: (t) => ipcRenderer.invoke('update:setToken', t),
  updateSetBeta: (on) => ipcRenderer.invoke('update:setBeta', on),
  updateOpenReleases: () => ipcRenderer.invoke('update:openReleases'),
  onUpdateEvent: (cb) => { ipcRenderer.on('update:event', (_e, data) => cb(data)); }
});
