// Pont sécurisé entre le renderer et le process principal.
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('skanfact', {
  loadData: () => ipcRenderer.invoke('data:load'),
  saveData: (data, force) => ipcRenderer.invoke('data:save', { data, force: !!force }),
  listDossiers: () => ipcRenderer.invoke('dossiers:list'),
  switchDossier: (id) => ipcRenderer.invoke('dossiers:switch', id),
  addDossier: (o) => ipcRenderer.invoke('dossiers:add', o),
  renameDossier: (o) => ipcRenderer.invoke('dossiers:rename', o),
  forgetDossier: (id) => ipcRenderer.invoke('dossiers:forget', id),
  renameDevice: (name) => ipcRenderer.invoke('device:rename', name),
  dataPath: () => ipcRenderer.invoke('data:path'),
  exportData: (data) => ipcRenderer.invoke('data:export', data),
  importData: (opts) => ipcRenderer.invoke('data:import', opts),
  unlock: (password) => ipcRenderer.invoke('data:unlock', password),
  lock: () => ipcRenderer.invoke('data:lock'),
  securityInfo: () => ipcRenderer.invoke('data:security'),
  setPassword: (opts) => ipcRenderer.invoke('data:setPassword', opts),
  externalBackupInfo: () => ipcRenderer.invoke('backups:externalInfo'),
  setExternalBackup: (dir) => ipcRenderer.invoke('backups:setExternal', dir),
  chooseExternalBackup: () => ipcRenderer.invoke('backups:chooseExternal'),
  openBackups: () => ipcRenderer.invoke('backups:open'),
  createBackup: (label) => ipcRenderer.invoke('backups:create', label),
  setTitle: (title) => ipcRenderer.send('window:title', title),
  setDirty: (dirty) => ipcRenderer.send('window:dirty', !!dirty),
  listBackups: () => ipcRenderer.invoke('backups:list'),
  pickLogo: (title) => ipcRenderer.invoke('logo:pick', title),
  exportPdf: (html, suggestedName) => ipcRenderer.invoke('pdf:export', { html, suggestedName }),
  exportPdfMany: (files, folderName) => ipcRenderer.invoke('pdf:exportMany', { files, folderName }),
  saveText: (suggestedName, content) => ipcRenderer.invoke('file:saveText', { suggestedName, content }),
  exportPdfSilent: (html, name) => ipcRenderer.invoke('pdf:exportSilent', { html, name }),
  saveTextSilent: (name, content) => ipcRenderer.invoke('file:saveSilent', { name, content }),
  composeMail: (opts) => ipcRenderer.invoke('mail:compose', opts),
  addAttachments: (docId) => ipcRenderer.invoke('attach:add', docId),
  // Lecture d'une photo de facture (4.2.0). `ocrRead` est le SEUL appel qui sort de l'ordinateur,
  // et il échoue proprement tant qu'aucune clé n'a été saisie.
  attachPath: (docId, path) => ipcRenderer.invoke('attach:addPath', { docId, path }),
  ocrStatus: () => ipcRenderer.invoke('ocr:status'),
  ocrSetKey: (key, model) => ipcRenderer.invoke('ocr:setKey', { key, model }),
  ocrPick: () => ipcRenderer.invoke('ocr:pick'),
  ocrRead: (path) => ipcRenderer.invoke('ocr:read', { path }),
  openAttachment: (docId, file) => ipcRenderer.invoke('attach:open', { docId, file }),
  revealAttachment: (docId, file) => ipcRenderer.invoke('attach:reveal', { docId, file }),
  removeAttachment: (docId, file) => ipcRenderer.invoke('attach:remove', { docId, file }),
  openPath: (p) => ipcRenderer.invoke('shell:open', p),
  showInFolder: (p) => ipcRenderer.invoke('shell:showInFolder', p),
  buildPack: (payload) => ipcRenderer.invoke('pack:build', payload),
  onPackProgress: (cb) => { ipcRenderer.on('pack:progress', (_e, d) => cb(d)); },
  changelog: () => ipcRenderer.invoke('app:changelog'),
  onMenuAction: (cb) => { ipcRenderer.on('menu:action', (_e, name) => cb(name)); },
  // mises à jour
  updateVersion: () => ipcRenderer.invoke('update:version'),
  updateCheck: () => ipcRenderer.invoke('update:check'),
  updateDownload: () => ipcRenderer.invoke('update:download'),
  updateInstall: () => ipcRenderer.invoke('update:install'),
  updateSetToken: (t) => ipcRenderer.invoke('update:setToken', t),
  updateOpenReleases: () => ipcRenderer.invoke('update:openReleases'),
  onUpdateEvent: (cb) => { ipcRenderer.on('update:event', (_e, data) => cb(data)); }
});
